USE [Willis]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Campsites](
	[CampsitesID] [int] IDENTITY(1,1) NOT NULL,
	[SiteNumber] [int] NULL,
	[Type] [varchar](20) NULL
 CONSTRAINT [PK_Action] PRIMARY KEY CLUSTERED 
(
	[CampsitesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = ON, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO


